#!/bin/sh

# Free error numbers -
# First unused error number: 62

# Configuration:

NUM_DETECTED=0

#############
#           #
# BEGIN CVS #
#           #
#############

# Current woring directory: base/project_working_dir
#
# Goal of this function: Check, that the working directory is clean, meaning:
# There are no files, that needs committing. So, all files should be committed
# to the repository OR being added to the VCSses way to being ignored, here
# .gitignore
#
# Resturn: Empty stdout, if everything is fine, exit code won't be checked.
cvs_check_work_dir_clean () {
	(
		cvs up 2>&1 || echo "Houston, we have a problem"
	) | grep -v "^cvs update: Updating "
}

# Current woring directory: base/project_working_dir
#
# Tag current version. In case of CVS, we tagged remotely, because we would
# cvs up into a carefully prepared mostly empty working directory and would
# get exactly the tagged files this way, preventing inconsistencies in case
# of a race between us cvs up'dating and someone else cvs commit'ting. In
# case of git, since we're using out local clone of the repository anyways,
# this step isn't needed at all. We'll tag later.
cvs_rtag () {
	tag_name="$1"
	
	cvs rtag -d "$tag_name" "$package"
}

# Current woring directory: base
cvs_clone () {
	mkdir -p "$TEMP/$package-$version-$VCS_NAME_LC/CVS" || exit 47
	cp "$package"/CVS/{Repository,Root} "$TEMP/$package-$version-$VCS_NAME_LC/CVS" || exit 40
	touch "$TEMP/$package-$version-$VCS_NAME_LC/CVS/Entries" || exit 52
	
	(
		cd "$TEMP/$package-$version-$VCS_NAME_LC" || exit 50
		cvs up 2>/dev/null || exit 51
	) || exit $?
	cp -a "$TEMP/$package-$version-$VCS_NAME_LC" "$TEMP/$package-$version-src" || exit 48
	
	find "$TEMP/$package-$version-src" -depth -type d -name CVS -exec rm -fr {} \;
	fcd -d -i "$TEMP/$package-$version-$VCS_NAME_LC" "$TEMP/$package-$version-src"
#	find "$TEMP/$package-$version-src" -name '.#*' -exec rm {} \;
}
	
# Current woring directory: base/project_working_dir
cvs_commit () {
	msg="$1"
	shift
	
	cvs commit -m "$msg" "$@"
}

# Current woring directory: base/project_working_dir
cvs_tag () {
	tag_name="$1"
	
	cvs tag "$tag_name" .
}

###########
#         #
# END CVS #
#         #
###########

#############
#           #
# BEGIN GIT #
#           #
#############

# Current woring directory: base/project_working_dir
#
# Goal of this function: Check, that the working directory is clean, meaning:
# There are no files, that needs committing. So, all files should be committed
# to the repository OR being added to the VCSses way to being ignored, here
# .gitignore
#
# Resturn: Empty stdout, if everything is fine, exit code won't be checked.
git_check_work_dir_clean () {
	git status --porcelain=1
}

# Current woring directory: base/project_working_dir
#
# Tag current version. In case of CVS, we tagged remotely, because we would
# cvs up into a carefully prepared mostly empty working directory and would
# get exactly the tagged files this way, preventing inconsistencies in case
# of a race between us cvs up'dating and someone else cvs commit'ting. In
# case of git, since we're using out local clone of the repository anyways,
# this step isn't needed at all. We'll tag later.
git_rtag () {
	true
}

# Current woring directory: base
git_clone () {
	git clone --shared "$package" "$TEMP/$package-$version-src" || exit 51
	
	mkdir "$TEMP/$package-$version-$VCS_NAME_LC" || exit 47
	
	mv "$TEMP/$package-$version-src/.git" "$TEMP/$package-$version-$VCS_NAME_LC" || exit 48
	
	rm "$TEMP/$package-$version-$VCS_NAME_LC/.git/objects/info/alternates"
}

# Current woring directory: base/project_working_dir
git_commit () {
	msg="$1"
	shift
	
	git add "$@"
	git commit -m "$msg"
}

# Current woring directory: base/project_working_dir
git_tag () {
	tag_name="$1"
	
	git tag "$tag_name"
}

###########
#         #
# END GIT #
#         #
###########

test -d  CVS && { DETECTED_CVS=true; let NUM_DETECTED=NUM_DETECTED+1; VCS_NAME_LC=cvs; } || DETECTED_CVS=false
test -d .git && { DETECTED_GIT=true; let NUM_DETECTED=NUM_DETECTED+1; VCS_NAME_LC=git; } || DETECTED_GIT=false

if test "$NUM_DETECTED" != 1
then
	echo "Currently, this script supports the following version control systems:" >&2
	echo >&2
	echo -n "       " >&2
	echo -n " CVS" >&2
	echo -n " git" >&2
	echo >&2
	echo >&2
	echo "Patches to support more VCSses are welcome." >&2
	exit 53
fi

if test "$1" == "--test"
then
	TESTING=true
	shift
else
	TESTING=false
fi

if $TESTING
then
	# Directory where to put the (compressed) .tar files
	ARCHIVE=archive.test
	
	# Directory where to search and put to the -src and -cvs directories for the previous version.
	TEMP=.version-control.test
else
	# Directory where to put the (compressed) .tar files
	ARCHIVE=archive
	
	# Directory where to search and put to the -src and -cvs directories for the previous version.
	TEMP=.version-control
fi

#
# Note: I use some 'sync's to make this action something crash-stable. But if
#       the computer crashes you might still be needed to 'repair' something so
#       that this all will work again. (But there should not be any risk of
#       data loosing at all - that is the reason for the many 'sync's ...)
#

if ! test -x "$(type -p bestzip)"
then
	echo "You have to install the package bothie-utils to use this feature. Sorry." >&2
	exit 29
fi

action="$1"

prev_major="$(cat .major)"
prev_minor="$(cat .minor)"
prev_patch="$(cat .patch)"
prev_version="$prev_major.$prev_minor.$prev_patch"

case "$action" in
	major)
		major=$(($prev_major+1))
		minor=0
		patch=0
		;;
	
	minor)
		major=$prev_major
		minor=$(($prev_minor+1))
		patch=0
		;;
	
	patch)
		major=$prev_major
		minor=$prev_minor
		patch=$(($prev_patch+1))
		;;
	
	*)
		echo "Unkown action. Valid actions are major, minor and patch"
		exit 30
		;;
esac

version="$major.$minor.$patch"

if test $(grep "^package *= *" Makefile | wc -l) != 1
then
	echo "Couldn't determine package name [1]"
	exit 31
fi

package="$(grep "^package *= *" Makefile | sed -e 's/^package *= *//')"

if test $(ls -id . ../$package | wc -l) != 2
then
	echo "Couldn't determine package name [2]"
	exit 32
fi

ls -id . ../$package | (
	read inode1 name1
	read inode2 name2
	
	if test "$inode1" != "$inode2"
	then
		echo "Couldn't determine package name [3]"
		exit 33
	fi
	
	exit 0
) || exit 34

if $TESTING
then
	rm -fr \
		"../$TEMP/$package-$version-src/" \
		"../$TEMP/$package-$version-cvs" \
		"../$ARCHIVE/$package-$version-src.tar"* \
		"../$ARCHIVE/$package-$version-cvs.tar"* \
		"../$ARCHIVE/$package-$version-src.diff"* \

fi
if test -d "../$TEMP/$package-$version-src" \
|| test -d "../$TEMP/$package-$version-cvs" \
|| test -f "../$ARCHIVE/$package-$version-src.tar"* \
|| test -f "../$ARCHIVE/$package-$version-cvs.tar"* \
|| test -f "../$ARCHIVE/$package-$version-src.diff"*
then
	echo "There is a file or directory in the way"
	exit 35
fi

if test -n "$(${VCS_NAME_LC}_check_work_dir_clean)"
then
	echo "There is a problem concerning $VCS_NAME_LC. Please make sure to have all files up to "
	echo "date (i.e. commit your changes) and have all files either $VCS_NAME_LC add'ed or "
	echo ".${VCS_NAME_LC}ignore'd."
	if $TESTING
	then
		echo "IGNORING PROBLEM, AS WE ARE ONLY TESTING ANYWAYS"
	else
		exit 36
	fi
fi

if ! $TESTING
then
	echo "Tagging current version $package-$major-$minor-$patch ..."
	${VCS_NAME_LC}_rtag $package-$major-$minor-$patch || exit 37
fi

(
	cd ..
	
	mkdir -p "$ARCHIVE" || exit 49
	
	${VCS_NAME_LC}_clone || exit $?
	
	echo "$major" > "$TEMP/$package-$version-src/.major" || exit 46
	echo "$minor" > "$TEMP/$package-$version-src/.minor" || exit 45
	echo "$patch" > "$TEMP/$package-$version-src/.patch" || exit 44
	
	for part in src $VCS_NAME_LC
	do
		if test "$part" == src
		then
			if test -d "$TEMP/$package-$prev_version-$part"
			then
				(
					cd "$TEMP" || exit 39
					test -z "$( (
						diff -urN \
							"$package-$prev_version-$part" \
							"$package-$version-$part" > \
							"$package-$prev_version-$version-$part.diff"
					) 2>&1)" || exit 42
				) || exit $?
				mv "$TEMP/$package-$prev_version-$version-$part.diff" "$ARCHIVE" || exit 43
				
				bestzip "$ARCHIVE/$package-$prev_version-$version-$part.diff" \
				&& rm "$ARCHIVE/$package-$prev_version-$version-$part.diff"
			fi || exit $?
		fi || exit $?
		
		(
			cd "$TEMP"
			tar c "$package-$version-$part"
		) > "$ARCHIVE/$package-$version-$part.tar" || exit 41
		
		bestzip "$ARCHIVE/$package-$version-$part.tar" && rm "$ARCHIVE/$package-$version-$part.tar"
	done || exit $?
) || exit $?

if ! $TESTING
then
	sync; sync; sync ##################### DISK WRITE BARRIER #####################
	
	echo "$patch" > ".patch.new" || exit 54
	echo "$minor" > ".minor.new" || exit 55
	echo "$major" > ".major.new" || exit 56
	
	sync; sync; sync ##################### DISK WRITE BARRIER #####################
	
	rm ".major" ".minor" ".patch" || exit 57
	
	sync; sync; sync ##################### DISK WRITE BARRIER #####################
	
	mv .patch.new .patch || exit 58
	mv .minor.new .minor || exit 59
	mv .major.new .major || exit 60
	
	sync; sync; sync ##################### DISK WRITE BARRIER #####################
	
	${VCS_NAME_LC}_commit "AUTOMATIC COMMIT [make-release]: Update version for make $action from $prev_version to $version" .patch .minor .major || exit 61
	
	echo "Tagging current version $package-$major-$minor-$patch a second time ..."
	${VCS_NAME_LC}_tag $package-$major-$minor-$patch || exit 38
fi

exit 0
