#!/bin/sh

if test -z $1; then
	what=all
else
	what=$1
	if test -f $1; then
		mv $1 $1~
	fi
fi

if test -z $2; then
	mydir=.
else
	mydir=$2
fi

#make --no-print-directory $what 2>&1 | \
#sed -f $mydir/script.sed | \
#sort -u | \
#grep -G "^#.*$" || true

make --no-print-directory $what 2>&1 | \
sed -f $mydir/script.sed | \
sort -u || true
